spring.application.name=taskboard
server.port=8100
spring.datasource.url=jdbc:mysql://localhost:3306/task_board?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# MyBatis-Plus
mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.type-aliases-package=com.taskboard.entity
mybatis-plus.configuration.map-underscore-to-camel-case=true
# å¯ç¨debugæ¨¡å¼æ¥çè¯¦ç»éè¯¯ä¿¡æ¯
debug=true
